name: DeployGHPages
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: yarn install
    - name: Running build
      run: yarn build
    - name: GitHub Pages Deploy
      uses: maxheld83/ghpages@v0.2.1
